# where to listen
network: 192.168.1.0/24

SSDP:
    device_type: urn:schemas-upnp-org:device:labManager

admin:
    server: localhost
    port: 8000

SMB:
    server: srv2.humlab.lu.se
    domain: UW  # domain for users (may be overridden by LDAP reply)
    projects:
        format: ^\d{4}-\d{2}\$$ # regex to match project shares
        remove_trailing: $      # part to remove from end of project share name

toems:
    server: pfsense-dc.humlab.lu.se
    port:   10022
    images:
        format: ^\d{4}-\d{2}    # regex to match project image files

login:
    hint: lucat id, without @lu.se

clients:
    - name: STATION01
      MAC:  0C-9D-92-1F-E6-04
    - name: STATION02
      MAC:  0C-9D-92-1F-94-12
    - name: STATION03
      MAC:  04-D4-C4-5B-1F-95
    - name: STATION04
      MAC:  04-D4-C4-5B-63-29
    - name: STATION05
      MAC:  0C-9D-92-C3-15-F8
    - name: STATION06
      MAC:  0C-9D-92-1F-94-9A
    - name: STATION07
      MAC:  0C-9D-92-C3-15-7C
    - name: STATION08
      MAC:  0C-9D-92-C3-15-16
    - name: STATION09
      MAC:  0C-9D-92-C4-26-86
    - name: STATION10
      MAC:  0C-9D-92-C3-15-1A
    - name: STATION11
      MAC:  0C-9D-92-C3-15-66
    - name: STATION12
      MAC:  0C-9D-92-C4-24-70
    - name: STATION13
      MAC:  0C-9D-92-C3-15-60
    - name: STATION14
      MAC:  0C-9D-92-C3-15-98
    - name: STATION15
      MAC:  0C-9D-92-C3-14-F2
    - name: STATION16
      MAC:  0C-9D-92-C3-15-54
    - name: MASTER
      MAC:  0C-9D-92-C3-15-EE

tasks:
    - name: ping
      type: Shell command
      payload: ping 8.8.8.8
    - name: Wake Computer
      type: Wake on LAN
    - name: Start ET Manager
      type: Shell command
      payload: '"C:\Users\Administrator\Desktop\Eye Tracker Manager.lnk"'
    - name: Start Tobii Pro Lab
      type: Shell command
      payload: '"C:\Users\Administrator\Desktop\Tobii Pro Lab (x64).lnk"'
    - name: Start Breakout Demo
      type: Shell command
      payload: '"C:\Users\Administrator\Desktop\Run breakout demo.lnk"'
    - name: Stop ET Manager
      type: Shell command
      payload: taskkill /t /f /im TobiiProEyeTrackerManager.exe
    - name: Stop Tobii Pro Lab
      type: Shell command
      payload: taskkill /t /f /im TobiiProLab.exe
    - name: Stop Python
      type: Shell command
      payload: taskkill /t /f /im python.exe
    - name: Stop Matlab
      type: Shell command
      payload: taskkill /t /f /im matlab.exe
    - name: Restart Computers
      type: Shell command
      payload: shutdown -r -t 0
    - name: Shutdown Computers
      type: Shell command
      payload: shutdown -s -t 0