:tool-name: master

:repo-home: https://github.com/dcnieho/labManager/tree/master
:doc-images: https://github.com/dcnieho/labManager/raw/master/docs

image:https://img.shields.io/pypi/v/labManager-{tool-name}.svg[PyPI Latest Release, link=https://pypi.org/project/labManager-{tool-name}/] image:https://img.shields.io/pypi/pyversions/labManager-{tool-name}.svg[Python version support, link=https://pypi.org/project/labManager-{tool-name}/]

== labManager v1.0.0
System for managing multi-station multi-tenant lab setups - {tool-name}

=== Example script
An example script for running the labManager {tool-name} script is link:{repo-home}/example-scripts/{tool-name}.py[provided here].

=== Configuration
The below shows the schema used for parsing the configuration file, using link:https://hitchdev.com/strictyaml/[StrictYAML's notation].
An link:link:{repo-home}/example-configs/{tool-name}.yaml[example configuration file] is also available.

[source,python,indent=0]
----
    'network': s.Str(),                                                     # Network on which to discover clients, e.g. 10.0.1.0/24
    'service_discovery_protocol': s.Enum(['MDNS','SSDP']),                  # Protocol to use for client discovery, MDNS or SSDP
    s.Optional('MDNS'): s.Map({
        'service': s.Str(),                                                 # service name to discover when using MDNS, e.g. _master._labManager._tcp.local.
    }),
    s.Optional('SSDP'): s.Map({
        'device_type': s.Str(),
    }),
    s.Optional('projects'): s.Map({
        'name_table': s.MapPattern(s.Str(), s.Str()),
    }),
    s.Optional('base_image_name_table'): s.MapPattern(s.Str(), s.Str()),
    s.Optional('SMB'): s.Map({
        'server': s.Str(),
        'domain': s.Str(),
        'projects': s.Map({
            'format': s.Str(),
            s.Optional('remove_trailing', default=''): s.Str(),
        }),
        'mount_share_on_client': s.Bool(),
        'mount_drive_letter': s.Str(),
        'mount_only_known_clients': s.Bool(),
    }),
    s.Optional('admin'): s.Map({
        'server': s.Str(),
        'port': s.Int(),
    }),
    s.Optional('toems'): s.Map({
        'server': s.Str(),
        'port': s.Int(),
        'images': s.Map({
            'format': s.Str(),
        }),
        s.Optional('pre_upload_script'): s.Str(),
        s.Optional('image_info_script'): s.Str(),
        s.Optional('image_info_script_partition'): s.Int(),
    }),
    s.Optional('login'): s.Map({
        'hint': s.Str(),
    }),
    s.Optional('clients'): s.Seq(
        s.Map({
            'name': s.Str(),
            'MAC' : s.CommaSeparated(s.Str()),
        })
    ),
    s.Optional('tasks'): s.Seq(
        s.Map({
            'name': s.Str(),
            'type': s.Enum(task.types),
            s.Optional('payload', default=''): s.Str(),
            s.Optional('payload_type', default='text'): s.Enum(['text','file']),
            s.Optional('cwd', default=''): s.Str(),
            s.Optional('env', default=''): s.Str(),
            s.Optional('interactive', default=False): s.Bool(),
            s.Optional('python_unbuffered', default=False): s.Bool(),
        }),
    ),
----

=== Standalone deployment
One simple way to make a standalone install of the app is to download https://winpython.github.io/[WinPython], e.g. the latest 3.10.x version.
I think this is recommended instead of using a system-wide or user installation of Python, so that users of the computer are unlikely to accidentally interfere with the Python distribution that runs the management tools.

Do as follows:

1. Download the dot version, not the full package, e.g. `Winpython64-3.10.11.1dot`.
2. Run the downloaded exe, which unzips the WinPython files.
3. Take the python folder from the unzipped files (e.g. `python-3.10.11.amd64`), you do not need the rest. This is your python distribution. Put it where you want on the disk.
4. Open a command prompt in the root of the Python installation. Install the wanted labManager packages into it using, e.g., `.\python.exe -m pip install labManager-{tool-name}`.
5. Finally use the `python.exe` in the folder to execute your script, such the link:{repo-home}/example-scripts/{tool-name}.py[example script] to launch this tool.
