name: Build readme


on:
  workflow_dispatch:
  push:
    paths:
      - README-source.adoc


jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce readme
        run: asciidoctor-reducer -o README.adoc README-source.adoc

    # now convert asciidoc to markdown
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i downdoc

      - name: Convert asciidoc to markdown
        run: npx downdoc -o test.md README.adoc

    # done, commit
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          add: '["README.adoc", "test.md"]'
          author_name: Diederick Niehorster
          author_email: dcnieho@gmail.com