name: Build readme


on:
  workflow_dispatch:
  push:
    paths:
      - '**.adoc'

env:
  DIRLIST: './labManager-client/,./labManager-master/'


jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce readme
        run: |
          IFS="," read -a myarray <<< ${{ env.DIRLIST }}
          for i in "${myarray[@]}"; do
            echo "Processing: ${i}"
            asciidoctor-reducer -o ${i}/README.adoc ${i}/README-source.adoc
            ls ${i}
          done

    # now convert asciidoc to markdown
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i downdoc

      - name: Convert asciidoc to markdown
        run: |
          IFS="," read -a myarray <<< ${{ env.DIRLIST }}
          for i in "${myarray[@]}"; do
            echo "Processing: ${i}"
            npx downdoc -o ${i}/README.md ${i}/README.adoc
            ls ${i}
          done

    # done, commit
      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          add: '["README.adoc", "test.md"]'
          author_name: Diederick Niehorster
          author_email: dcnieho@gmail.com